// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Event struct {
	ID                    string         `json:"id"`
	User                  string         `json:"user"`
	Name                  string         `json:"name"`
	Description           *string        `json:"description"`
	Capacity              int            `json:"capacity"`
	Duration              int            `json:"duration"`
	StartDate             time.Time      `json:"startDate"`
	EndDate               time.Time      `json:"endDate"`
	RegistrationStartDate time.Time      `json:"registrationStartDate"`
	RegistrationEndDate   time.Time      `json:"registrationEndDate"`
	Latitude              float64        `json:"latitude"`
	Longitude             float64        `json:"longitude"`
	Public                bool           `json:"public"`
	Participants          []*Participant `json:"participants"`
}

type Invitation struct {
	User  string `json:"user"`
	Event string `json:"event"`
}

type Location struct {
	Latitude  *float64 `json:"latitude"`
	Longitude *float64 `json:"longitude"`
	Distance  *int     `json:"distance"`
}

type NewEvent struct {
	User                string     `json:"user"`
	Name                string     `json:"name"`
	Description         *string    `json:"description"`
	Capacity            int        `json:"capacity"`
	Latitude            float64    `json:"latitude"`
	Longitude           float64    `json:"longitude"`
	Duration            int        `json:"duration"`
	StartDate           time.Time  `json:"startDate"`
	RegistrationEndDate *time.Time `json:"registrationEndDate"`
	Public              bool       `json:"public"`
}

type Participant struct {
	User string `json:"user"`
}

type Period struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type Upcoming struct {
	Date     *time.Time `json:"date"`
	Duration *int       `json:"duration"`
}

type UpdateEvent struct {
	ID               string   `json:"id"`
	Name             *string  `json:"name"`
	Description      *string  `json:"description"`
	Capacity         *int     `json:"capacity"`
	Latitude         *float64 `json:"latitude"`
	Longitude        *float64 `json:"longitude"`
	EventDate        *Period  `json:"eventDate"`
	RegistrationDate *Period  `json:"registrationDate"`
	Public           *bool    `json:"public"`
}
